# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

client:
  region: ${CLIENT_CLOUD_REGION}
  clusterId: ${CLIENT_CLOUD_CLUSTER_ID}
  clientId: ${CLIENT_CLOUD_CLIENT_ID}
  clientSecret: ${CLIENT_CLOUD_CLIENT_SECRET}

server:
  port: 8082
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
