# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

#exporter or operate
timers.from: exporter
zeebe.client:
  broker.gatewayAddress: 127.0.0.1:26500
  security.plaintext: true 
#zeebe.client:
#  cloud:
#    region: bru-2
#    clusterId: debcfc76-bbc4-4b08-b290-8f21848e386a
#    clientId: wHjN3io7jRkiw0fY7.~~Ux0JUoQzw0om
#    clientSecret: fx_K_OOZBd9wRFr_yLSFMAhSY3udZZlArNmQx~jDIVddStAsd8ofhY3cWDtq2b2~
      
gateway.actuator: http://127.0.0.1:9600/actuator
operate:
  selfmanaged:
    url: http://localhost:8081
    clientId: dataloader
    clientSecret: nXKnTqcnnYKL0ysJqGhwk0W6UWq2QYLM
    keycloakUrl: http://localhost:18080
  #cloud:
  #  region: bru-2
  #  clusterId: debcfc76-bbc4-4b08-b290-8f21848e386a
  #  clientId: wHjN3io7jRkiw0fY7.~~Ux0JUoQzw0om
  #  clientSecret: fx_K_OOZBd9wRFr_yLSFMAhSY3udZZlArNmQx~jDIVddStAsd8ofhY3cWDtq2b2~

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
